font_size: 22
theme: pywal
tree_1:
  general:
    github: "https://www.github.com/alissondangelo"
    gmail: "https://mail.google.com/"
  reddit:
    frontpage: 
      - "https://www.reddit.com/"
      - "front page"
    unixporn: "https://www.reddit.com/r/unixporn/"
tree_2:
  other:
    archwiki: 
      - "https://archlinux.org/"
      - "arch wiki"
    youtube: "https://www.youtube.com/"